version: 2
updates:
  - package-ecosystem: npm
    directory: /plugins/multi-gmail
    schedule:
      interval: weekly
    groups:
      npm-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
