version: 2
updates:
  - package-ecosystem: npm
    directory: /plugins/multi-gmail
    schedule:
      interval: weekly
    groups:
      npm-dependencies:
        patterns: ["*"]
    ignore:
      - dependency-name: zod
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
